# Generated by Django 5.1 on 2024-08-24 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('creation_date', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150, unique=True)),
                ('subtitle', models.IntegerField()),
                ('date', models.CharField(max_length=30)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='images/news/')),
            ],
            options={
                'db_table': 'News',
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_id', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150, unique=True)),
                ('alias', models.CharField(max_length=150, unique=True)),
                ('position', models.CharField(max_length=150, unique=True)),
                ('dorsal', models.CharField(max_length=150, unique=True)),
                ('birthday_date', models.CharField(max_length=150, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/players/')),
                ('is_active', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'Players',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(max_length=150, unique=True)),
                ('prize', models.CharField(max_length=150, unique=True)),
                ('is_active', models.CharField(max_length=150, unique=True)),
                ('creation_date', models.CharField(max_length=150, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/products/')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.CharField(max_length=150, unique=True)),
                ('web_url', models.CharField(max_length=150, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/sponsors/')),
            ],
            options={
                'db_table': 'Sponsors',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('html', models.CharField(max_length=150000)),
                ('news_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='judesaBackend.news')),
            ],
            options={
                'db_table': 'Tags',
            },
        ),
    ]
