# Generated by Django 5.1.1 on 2024-09-17 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judesaBackend', '0002_alter_news_id_alter_products_id_alter_tags_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='preview_image',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tags',
            name='news_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_id', to='judesaBackend.news'),
        ),
    ]
