# Generated by Django 5.1.1 on 2024-09-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judesaBackend', '0003_alter_news_preview_image_alter_tags_news_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='html',
        ),
        migrations.AddField(
            model_name='tags',
            name='alt',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tags',
            name='class_style',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tags',
            name='content',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tags',
            name='link',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tags',
            name='type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
