# Generated by Django 5.1.1 on 2024-09-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judesaBackend', '0004_remove_tags_html_tags_alt_tags_class_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='alt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='class_style',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='content',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='link',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
