# Generated by Django 5.1.1 on 2024-09-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judesaBackend', '0005_alter_tags_alt_alter_tags_class_style_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='alt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='class_style',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='content',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
