# Generated by Django 5.1.1 on 2024-09-17 15:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judesaBackend', '0006_alter_tags_alt_alter_tags_class_style_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'Staff',
            },
        ),
        migrations.RemoveField(
            model_name='news',
            name='date',
        ),
        migrations.AddField(
            model_name='categories',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='news',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='players',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsors',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='preview_image',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='news',
            name='subtitle',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='birthday_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='players',
            name='dorsal',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='players',
            name='image',
            field=models.CharField(default='', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='players',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(default='', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tags',
            name='alt',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='class_style',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='content',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='categories',
            name='delegate',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='delegate_id', to='judesaBackend.staff'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categories',
            name='trainer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='trainer_id', to='judesaBackend.staff'),
            preserve_default=False,
        ),
    ]
