# Generated by Django 5.1.1 on 2024-09-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judesaBackend', '0007_staff_remove_news_date_categories_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
