# Generated by Django 5.1.1 on 2024-09-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judesaBackend', '0010_alter_players_category_id_matches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matches',
            name='judesa_score',
        ),
        migrations.RemoveField(
            model_name='matches',
            name='rival_score',
        ),
        migrations.AddField(
            model_name='matches',
            name='local_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matches',
            name='visitant_score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
