# Generated by Django 5.1.1 on 2024-09-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judesaBackend', '0011_remove_matches_judesa_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matches',
            name='location',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='rival',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='players',
            name='birthday_date',
            field=models.DateField(),
        ),
    ]
