# Generated by Django 5.1.1 on 2024-09-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judesaBackend', '0014_alter_staff_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='image',
            field=models.CharField(default='', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
