# Generated by Django 5.1.1 on 2024-09-24 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judesaBackend', '0017_alter_staff_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='image',
        ),
    ]
