# Generated by Django 5.1.1 on 2024-09-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judesaBackend', '0021_alter_categories_delegate_alter_categories_trainer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.CharField(default='', max_length=150),
        ),
    ]
